#!/bin/sh

# Hook created by Jaqueline Kirino
# Automatically adds branch name and branch description to every commit message.
#   Version: 2.0

REGEX="^(\[([[:alpha:]]{1,3}-[[:digit:]]{1,3})] -|Merge) " #JIRA PATTERN string 1 to 3, and number 1 to 3 like '[ABC-123] - ' or '[z-2]'
MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"

# If commit is already good, take it
if [[ $FILE_CONTENT =~ $REGEX ]]; then
  exit 0
fi

ORIGBRANCH="$(git rev-parse --abbrev-ref HEAD)"
# Line below will be used when branch pattern is feature/ABC-123
# BRANCHREMOVED="${ORIGBRANCH%%/*}"            # remove all text after / and store in variable BRANCHREMOVED
# change also variable name to branchremoved
POSITION="$(( ${#ORIGBRANCH} + 1 ))"  # get string length of $BRANCHREMOVED + 1
BRANCH=${ORIGBRANCH:POSITION}

if [[ ! $BRANCH ]]; then
  BRANCH=BRANCHREMOVED
fi

echo "Prepending branch information \"[$BRANCH] - \"..."
echo "[$BRANCH] - $FILE_CONTENT" > $MSG_FILE
echo "" >> $MSG_FILE
